#pragma once

#include "NotoSans_Bold731fpt8b.hpp"
#include "NotoSans_Medium731fpt8b.hpp"
#include "NotoSans_Regular731fpt8b.hpp"
#include "NotoSans_SemiBold731fpt8b.hpp"
#include "NotoSans_SemiCondensed731fpt8b.hpp"
#include "NotoSans_SemiCondensedBold731fpt8b.hpp"
#include "NotoSans_SemiCondensedMedium731fpt8b.hpp"
#include "NotoSans_SemiCondensedSemiBold731fpt8b.hpp"
#include "OpenSans_Bold731fpt8b.hpp"
#include "OpenSans_Medium731fpt8b.hpp"
#include "OpenSans_Regular731fpt8b.hpp"
#include "OpenSans_SemiBold731fpt8b.hpp"
#include "OpenSans_SemiCondensed_Bold731fpt8b.hpp"
#include "OpenSans_SemiCondensed_Medium731fpt8b.hpp"
#include "OpenSans_SemiCondensed_Regular731fpt8b.hpp"
#include "OpenSans_SemiCondensed_SemiBold731fpt8b.hpp"
